import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '@components/Nav'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-gray-100" lang="en">
      <body className={inter.className + ' h-full'}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
